import { Trait } from '../context/types';

const traitsLTMale = [
  'Artimas',
  'Atviras',
  'Drovus',
  'Šiltas',
  'Mielas',
  'Linksmas',
  'Taikus',
  'Ryžtingas',
  'Atkaklus',
  'Drąsus',
  'Išsigandęs',
  'Žavus',
  'Išdidus',
  'Ramus',
  'Nusiminęs',
  'Pašėlęs',
  'Lėtas',
  'Abejingas',
  'Liūdnas',
  'Globojantis',
  'Užsispyręs',
  'Užjaučiantis',
  'Stiprus',
  'Žingeidus',
  'Suirzęs',
  'Draugiškas',
  'Padedantis',
  'Darbštus',
  'Išsiblaškęs',
  'Sąmojingas',
  'Jausmingas',
  'Uždaras',
  'Pavydus',
  'Džiaugsmingas',
  'Džiugus',
  'Tiesus',
  'Apsimiegojęs',
  'Taktiškas',
  'Nuoširdus',
  'Dėkingas',
  'Nenustygstantis vietoje',
  'Atsakingas',
  'Pavargęs',
  'Užsisklendęs',
  'Dosnus',
  'Patikimas',
  'Tobulėjantis',
  'Narsus',
  'Santūrus',
  'Pritariantis',
  'Klystantis',
];

const traitsLTFemale = [
  'Artima',
  'Atvira',
  'Drovi',
  'Šilta',
  'Miela',
  'Linksma',
  'Taiki',
  'Ryžtinga',
  'Atkakli',
  'Drąsi',
  'Išsigandusi',
  'Žavi',
  'Išdidi',
  'Rami',
  'Nusiminusi',
  'Pašėlusi',
  'Lėta',
  'Abejinga',
  'Liūdna',
  'Globojanti',
  'Užsispyrusi',
  'Užjaučianti',
  'Stipri',
  'Žingeidi',
  'Suirzusi',
  'Draugiška',
  'Padedanti',
  'Darbšti',
  'Išsiblaškiusi',
  'Sąmojinga',
  'Jausminga',
  'Uždara',
  'Pavydi',
  'Džiaugsminga',
  'Džiugi',
  'Tiesi',
  'Apsimiegojusi',
  'Taktiška',
  'Nuoširdi',
  'Dėkinga',
  'Nenustygstanti vietoje',
  'Atsakinga',
  'Pavargusi',
  'Užsisklendusi',
  'Dosni',
  'Patikima',
  'Tobulėjanti',
  'Narsi',
  'Santūri',
  'Pritarianti',
  'Klystanti',
];

export default function getTraits(gender: 'male' | 'female') : Trait[] {
  if (gender === 'male') return traitsLTMale.map((name, id) => ({ name, id }));
  return traitsLTFemale.map((name, id) => ({ name, id }));
}
