const traitsLT = [
    'Artimas',
    'Atviras',
    'Drovus',
    'Šiltas',
    'Mielas',
    'Linksmas',
    'Taikus',
    'Ryžtingas',
    'Atkaklus',
    'Drąsus',
    'Išsigandęs',
    'Žavus',
    'Išdidus',
    'Ramus',
    'Nusiminęs',
    'Pašėlęs',
    'Lėtas',
    'Abejingas',
    'Liūdnas',
    'Globojantis',
    'Užsispyręs',
    'Užjaučiantis',
    'Stiprus',
    'Žingeidus',
    'Suirzęs',
    'Draugiškas',
    'Padedantis',
    'Darbštus',
    'Išsiblaškęs',
    'Sąmojingas',
    'Jausmingas',
    'Uždaras',
    'Pavydus',
    'Džiaugsmingas',
    'Džiugus',
    'Tiesus',
    'Apsimiegojęs',
    'Taktiškas',
    'Nuoširdus',
    'Dėkingas',
    'Nenustygstantis vietoje',
    'Atsakingas',
    'Pavargęs',
    'Užsisklendęs',
    'Dosnus',
    'Patikimas',
    'Tobulėjantis',
    'Narsus',
    'Santūrus',
    'Pritariantis',
    'Klystantis'
]

export default function getTraits() : string[] {
    return traitsLT;
}